Membangun Antarmuka Halaman Pengaturan Ulang Kata Sandi
sensasi-apps/sensasi-pos pull request #177
Opened 2024-10-09 06:10 UTC by theozebua

Antarmuka halaman pengaturan ulang kata sandi telah selesai dibangun dan menyelesaikan isu #147. Tetapi, masih belum ada validasi untuk token pengaturan ulang kata sandi. Nanti akan dilanjutkan dengan isu #146.

Mungkin nanti struktur pengkodean akan di _refactor_, tetapi untuk sementara begini saja dulu.

2024-10-09 17:09 UTC, sensasi-delight approved these changes
GELAS KINK 🍻

2024-10-09 17:12 UTC, sensasi-delight commented
Ternyata lupa halaman ini untuk reset PIN juga, apa bisa diakomodir? @theozebua

2024-10-09 17:13 UTC, sensasi-delight requested changes
Lupa menambahkan input-input untuk reset PIN

2024-10-09 17:32 UTC, theozebua commented
> Lupa menambahkan input-input untuk reset PIN

Ohh berarti sekalian ganti PIN juga ya bang? Oke oke.
Untuk aturan PIN ini seperti apa bang? Apakah seperti biasa 6 angka atau bagaimana?

@sensasi-delight

2024-10-09 17:33 UTC, zainphp commented
betul hanya angka sepanjang 6 digit. juga jangan lupa untuk input konfirmasi PIN nya.

2024-10-09 17:38 UTC, theozebua commented
Oke, dimengerti 👌🏻

2024-10-10 09:36 UTC, theozebua commented
PIN _input fields_ telah ditambahkan sesuai dengan _requested changes_ pada https://github.com/sensasi-apps/sensasi-pos/pull/177#pullrequestreview-2357747229. Mohon di-_review_ bang @sensasi-delight 

Tadinya aku mau buat bentuk PIN _input_-nya kayak kotak-kotak gitu, tapi setelah kupikir-pikir nanti aja deh buat yang kayak gitu. 😄

2024-10-10 10:11 UTC, merged